### ISSUE TITLE
Update scripts.irssi.org

### ISSUE THREAD

**Issue by amckinlay** [lifeforms/irssi-smartfilter#10]
Update https://github.com/irssi/scripts.irssi.org/blob/master/scripts/smartfilter.pl so that irssi-smartfilter can be installed with scriptassist.

**Comment by mafgh** [comment]
Works for me

```
[(status)] /scriptassist install smartfilter
09:19 -!- Irssi: Loaded script smartfilter
09:19 ,--[ScriptAssist]
09:19 | o smartfilter installed
09:19 `--<install>->

09:20 smartfilter    ***/.irssi/scripts/smartfilter.pl
```

**Comment by cbzehner** [comment]
This should be complete once https://github.com/irssi/scripts.irssi.org/pull/474 is merged in.
