### ISSUE TITLE
Solved.

### ISSUE THREAD

**Issue by cco** [lifeforms/irssi-smartfilter#12]
Not an issue anymore.

**Comment by konomikitten** [comment]
Try running dos2unix on the script file and report back if that fixed it, all those errors look odd to me and makes me think you've got some windows line endings perhaps. Failing that can you please run md5sum on it and check if your hash matches mine.

`d2af55a7fa3e874affc1b173bdc18ecd  smartfilter.pl`

**Comment by ailin-nemui** [comment]
he downloaded the web page instead of the script, see:

Bareword found near ""en" class"

Bareword found near "<title>irssi"

**Comment by konomikitten** [comment]
@NiallBunting seems so hopefully they'll notice and download the correct file.

**Comment by shmup** [comment]
@cco someone should have told you, granted you may never see this, but don't edit Issue titles like this.

The issue being _closed_ is the Signal that it's been solved

**Comment by cco** [comment]
Sorry about that, I don't even remember making this issue report. Will take note in the future.

**Comment by shmup** [comment]
@cco no problem! But you can still close this issue if it's solved. :) It's in your hands (or the repo owner), as you opened the issue.

Cheers

**Comment by konomikitten** [comment]
Can someone close this, it's obviously solved?

**Comment by lifeforms** [comment]
🔒
