### ISSUE TITLE
Activate the script only in some channels

### ISSUE THREAD

**Issue by guiniol** [lifeforms/irssi-smartfilter#3]
Hello,

Would it be possible to hide the join/parts only in specified channels?
In small private channels, hiding join/parts is inconvenient.

Cheers

**Comment by lifeforms** [comment]
Thanks to @mrc0mmand, this functionality is now available! :)

To use it, first update your smartfilter.pl to the latest version. Then, to exclude your channels from smartfilter, do: `/set smartfilter_ignored_chans #smallchannel #anothersmallchannel`

**Comment by guiniol** [comment]
Awesome!! Thanks a lot to @mrc0mmand.

**Comment by chinese-soup** [comment]
Thank you, @mrc0mmand!
