### ISSUE TITLE
Should count the activity of queries or ignore them for filtering

### ISSUE THREAD

**Issue by konomikitten** [lifeforms/irssi-smartfilter#7]
Currently the script doesn't count the activity in a query so if a person who you are actively talking with in a query quits you won't see the event at all, neither in the channel or the query. This should be addressed.

**Comment by mrc0mmand** [comment]
This is indeed a problem. The easiest solution would be to ignore filtering on channels which don't begin with #. I think that should work for most of the cases and right now I can't think of any exception (but that basically depends on each IRC server's settings).

**Comment by konomikitten** [comment]
@mrc0mmand I think the most clean solution would be to use the "message private" signal to push their nick to the list. From the docs:

`fe-messages.c:
"message private", SERVER_REC, char *msg, char *nick, char *address`

In fact looking at the code I think the simple addition of this line in signals area at the bottom would work:

`Irssi::signal_add('message private', 'log');`

Might be a few issues with services that send messages but not like they're going to stay active for long, what do you think?

**Comment by konomikitten** [comment]
Also for the option of ignoring queries a simple check for the channel being undefined and returning out of the checkactive function would work, so there's two options as I see and the best one just needs to be picked.

Edit: To be honest returning out of the function seems like the best option to me, that means their quit / connect messages would only show up in the query and not in the channel which seems like the cleanest option to me, opinions?

Edit 2: Currently testing this addition to checkactive:

~~`# If channel is not defined we don't need to filter`~~
~~`if (not defined($channel)) {`~~
~~`return;`~~
~~`}`~~

Edit 3: Needed more adjustments after testing
`# If the channel is undefined or the channel is the same as the nick`
`# of the originating event it came from is a query, so return`
`if (not defined($channel) or (defined($channel) and $channel eq $nick)) {`
`return;`
`}`

Third attempt appears to be working with testing interested in others input on the solution or a better one.

**Comment by konomikitten** [comment]
Created a pull request for my fix for this issue. #9

**Comment by konomikitten** [comment]
Could someone please review the pull request it has been ages.

**Comment by lifeforms** [comment]
@KonomiKitten I'm sorry, I've been spending almost all my free time on another OSS project, and since there's no test cases for this script I have to play the manual CI bot (i.e try the code with various settings and scenarios etc). I'll do whatever I can to merge it next weekend.

**Comment by lifeforms** [comment]
I tested #9 and it looks great. Events are displayed fine in query windows. Thanks for the contribution ❤
